### ISSUE TITLE
How to reproduce the training process?

### ISSUE THREAD

**Issue by viking66666** [facebookresearch/SEAL#10]
Hi, 

Thanks for the great work! 
I only found the inference part in the code,  I wonder if you can share the training code and training data (or script to construct the training data)?

**Comment by mbevila** [comment]
Hi!

I have pushed  some scripts that should allow you to build the training data and then train the model. Please check out [https://github.com/facebookresearch/SEAL/tree/main/scripts/training](https://github.com/facebookresearch/SEAL/tree/main/scripts/training)!
