### ISSUE TITLE
Retrieval process

### ISSUE THREAD

**Issue by ZiluLii** [facebookresearch/SEAL#13]
Hi,
In the retrieval section of README, it says that To run prediction, launch the command: ....    --topics_format dpr --topics input.json \....
What's input.json here? Is it the NQ Test/KILT dev/ KILT test downstream task? 

Thank you!

**Comment by mbevila** [comment]
Hi,

It is the file you containing all the queries you use for prediction, as you said. The format is that used by DPR, e.g. (https://dl.fbaipublicfiles.com/dpr/data/retriever_results/single/nq-test.json.gz). We also support other formats (all those supported by pyserini + those that we define at https://github.com/facebookresearch/SEAL/blob/24322c9247a9d09ef8d5ae929b51de6a1d077c55/seal/data.py#L163).

**Comment by ZiluLii** [comment]
thank you!
