### ISSUE TITLE
Settings on NQ320K

### ISSUE THREAD

**Issue by ZiluLii** [facebookresearch/SEAL#14]
Hi, I'm wondering what's the settings of the SEAL on NQ320K dataset? (Originally I thought it was using the DPR embeddings, forgive me if I'm wrong, but it seems like DPR doesn't have it on NQ320K dataset.)
Thank you very much!

**Comment by mbevila** [comment]
Hi, what do you mean by _settings_? NQ320K is our replication of https://arxiv.org/abs/2202.06991, the authors of which, AFAIK, has not released code nor datasets. However, in another, independent, replication attempt (https://arxiv.org/pdf/2206.02743.pdf) datasets have been released. You could probably start with that. They SEAL numbers are a bit weird, but I know they are working on fixing that for their v2.

**Comment by ZiluLii** [comment]
I'm sorry but I couldn't find the dataset from NCI, could you please direct me to that if you know where to find it?

**Comment by mbevila** [comment]
https://drive.google.com/drive/folders/1510SvyYO06DTC6bVRQWMpAZRy6eYFtrZ?usp=sharing

**Comment by ZiluLii** [comment]
Thank you for directing me to this, can I also ask another question:
The documents in the dev set are not a strict subset of the document in the train set. Given that this is the case, how do you deal with the documents that are a part of the dev set but not the train set?
